import {
  Prerequisites,
  NewConcepts,
  Motivation,
  Intuition,
  Recall,
  Angles,
  Angle,
  Convergence,
  Derivation,
  Step,
  Example,
  Nuance,
  RealWorldML,
  MLConnection,
  Summary,
  CodeItYourself,
  ProblemSet,
  Quiz,
  Term,
  MarkDone,
  LifeLesson,
  StudyDepth,
} from "@/components/pedagogy";
import { RunnableCode, CodeBlock } from "@/components/code/RunnableCode";
import {
  FunctionPlot,
  VectorPlayground,
  GradientDescentLab,
} from "@/components/widgets/FunctionPlot";

export const mdxComponents = {
  Prerequisites,
  NewConcepts,
  Motivation,
  Intuition,
  Recall,
  Angles,
  Angle,
  Convergence,
  Derivation,
  Step,
  Example,
  Nuance,
  RealWorldML,
  MLConnection,
  Summary,
  CodeItYourself,
  ProblemSet,
  Quiz,
  Term,
  MarkDone,
  LifeLesson,
  StudyDepth,
  RunnableCode,
  CodeBlock,
  FunctionPlot,
  VectorPlayground,
  GradientDescentLab,
};
